import asyncio
import nest_asyncio
import json
import tempfile
from io import BytesIO

import streamlit as st
from dotenv import load_dotenv
from pptx import Presentation

from main import main

# Apply nest_asyncio to handle async loops in streamlit
asyncio.set_event_loop(asyncio.new_event_loop())
nest_asyncio.apply()

# Load environment variables
load_dotenv()

SLIDE_ICON = """
<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">
  <rect x="3" y="4" width="18" height="13" rx="2"></rect>
  <path d="M8 20h8"></path>
  <path d="M12 17v3"></path>
</svg>
"""

CHAT_ICON = """
<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">
  <path d="M21 15a3 3 0 0 1-3 3H8l-5 3V6a3 3 0 0 1 3-3h12a3 3 0 0 1 3 3z"></path>
</svg>
"""

UPLOAD_ICON = """
<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">
  <path d="M12 16V4"></path>
  <path d="m7 9 5-5 5 5"></path>
  <path d="M20 16.5v2.5a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2v-2.5"></path>
</svg>
"""


# Function to create PowerPoint slides
def create_pptx(slides_dict):
    prs = Presentation()
    title_slide_layout = prs.slide_layouts[0]
    content_slide_layout = prs.slide_layouts[1]

    # Add title slide
    title_slide = prs.slides.add_slide(title_slide_layout)
    title_slide.shapes.title.text = "Book Summary Slides"
    title_slide.placeholders[1].text = "Generated by Book Slide Generator"

    if slides_dict is None:
        raise ValueError("slides_dict is None. Cannot create PowerPoint slides.")

    for chapter, sections in slides_dict.items():
        for section, slide_markdown_list in sections.items():
            slide = prs.slides.add_slide(content_slide_layout)
            slide.shapes.title.text = f"{chapter} - {section}"
            content = slide.placeholders[1]
            content.text = _slides_to_plain_text(slide_markdown_list)

    return prs

def _slides_to_plain_text(slide_markdown_list):
    plain_lines = []
    for slide_markdown in slide_markdown_list:
        for line in slide_markdown.splitlines():
            cleaned = line.strip()
            if not cleaned:
                continue
            if cleaned.startswith("# "):
                plain_lines.append(cleaned[2:])
            else:
                plain_lines.append(cleaned)
        plain_lines.append("")
    return "\n".join(plain_lines).strip()


def _load_slides_into_state(json_path):
    with open(json_path, "r", encoding="utf-8") as file:
        slides_dict = json.load(file)

    pptx_io = BytesIO()
    create_pptx(slides_dict).save(pptx_io)

    st.session_state.slides_generated = True
    st.session_state.json_path = json_path
    st.session_state.slides_dict = slides_dict
    st.session_state.slide_index = 0
    st.session_state.pptx_bytes = pptx_io.getvalue()


def _render_chat_message(role, text):
    bubble_class = "chat-user" if role == "user" else "chat-assistant"
    label = "You" if role == "user" else "Assistant"
    st.markdown(
        f"""
        <div class="chat-bubble {bubble_class}">
            <div class="chat-label">{label}</div>
            <div>{text}</div>
        </div>
        """,
        unsafe_allow_html=True,
    )


st.set_page_config(page_title="Book Slide Generator", layout="wide")
st.markdown(
    """
    <style>
        :root {
            --ink: #d9e6ec;
            --charcoal: #131a20;
            --charcoal-soft: #1b252d;
            --slate: #2a3943;
            --slate-soft: #3a4b57;
            --cyan: #47c6db;
            --cyan-soft: #86dfec;
            --mist: #9db3be;
            --panel: rgba(24, 31, 38, 0.9);
            --panel-strong: rgba(18, 23, 29, 0.95);
            --shadow: 0 24px 72px rgba(5, 9, 12, 0.3);
        }
        .main {
            background:
                radial-gradient(circle at top left, rgba(71, 198, 219, 0.16), transparent 28%),
                radial-gradient(circle at top right, rgba(134, 223, 236, 0.08), transparent 30%),
                linear-gradient(180deg, #0d1318 0%, #141d24 100%);
            color: var(--ink);
        }
        .block-container {
            padding-top: 2rem;
            padding-bottom: 2rem;
        }
        .hero-shell {
            background: linear-gradient(135deg, rgba(28, 37, 45, 0.96), rgba(21, 28, 34, 0.95));
            border: 1px solid rgba(134, 223, 236, 0.1);
            border-radius: 28px;
            padding: 1.4rem 1.6rem;
            box-shadow: var(--shadow);
            margin-bottom: 1.4rem;
            animation: rise 0.5s ease-out;
        }
        .hero-kicker {
            display: inline-flex;
            align-items: center;
            gap: 0.45rem;
            padding: 0.35rem 0.75rem;
            border-radius: 999px;
            background: rgba(71, 198, 219, 0.14);
            color: var(--cyan-soft);
            font-size: 0.82rem;
            letter-spacing: 0.04em;
            text-transform: uppercase;
            margin-bottom: 0.8rem;
        }
        .hero-title {
            font-size: 2.4rem;
            line-height: 1.05;
            font-weight: 700;
            color: #ecf7fb;
            margin-bottom: 0.45rem;
        }
        .hero-copy {
            max-width: 52rem;
            color: rgba(217, 230, 236, 0.8);
            font-size: 1rem;
            line-height: 1.6;
        }
        .panel {
            background: var(--panel);
            border: 1px solid rgba(134, 223, 236, 0.08);
            border-radius: 24px;
            padding: 1.2rem;
            box-shadow: var(--shadow);
            animation: rise 0.55s ease-out;
            margin-bottom: 1.1rem;
        }
        .panel-title {
            display: flex;
            align-items: center;
            gap: 0.7rem;
            font-size: 1.05rem;
            font-weight: 700;
            color: var(--cyan-soft);
            margin-bottom: 0.9rem;
        }
        .panel-title svg {
            width: 20px;
            height: 20px;
        }
        .meta-strip {
            display: grid;
            grid-template-columns: repeat(3, minmax(0, 1fr));
            gap: 0.8rem;
            margin-bottom: 1rem;
        }
        .meta-card {
            padding: 0.8rem 0.95rem;
            border-radius: 18px;
            background: linear-gradient(180deg, rgba(43, 55, 64, 0.96), rgba(29, 39, 46, 0.96));
            border: 1px solid rgba(71, 198, 219, 0.16);
        }
        .meta-label {
            font-size: 0.72rem;
            text-transform: uppercase;
            letter-spacing: 0.06em;
            color: rgba(157, 179, 190, 0.72);
            margin-bottom: 0.25rem;
        }
        .meta-value {
            font-weight: 700;
            color: #eef8fb;
        }
        .slide-card {
            background: linear-gradient(180deg, rgba(35, 47, 56, 0.98), rgba(24, 33, 40, 0.98));
            border: 1px solid rgba(71, 198, 219, 0.1);
            border-radius: 24px;
            padding: 1.15rem 1.2rem;
            margin-bottom: 0.95rem;
            margin-top: 0.2rem;
            transform-origin: top;
            animation: cardIn 0.35s ease-out;
        }
        .nav-rail {
            display: flex;
            align-items: center;
            justify-content: center;
            min-height: 100%;
        }
        .slide-title {
            font-size: 1.15rem;
            font-weight: 700;
            color: #edf8fb;
            margin-bottom: 0.8rem;
        }
        .slide-line {
            color: rgba(217, 230, 236, 0.86);
            line-height: 1.55;
            margin: 0.28rem 0;
        }
        .slide-heading {
            font-weight: 700;
            color: var(--cyan-soft);
        }
        .chat-shell {
            max-height: 520px;
            overflow-y: auto;
            padding-right: 0.25rem;
        }
        .chat-bubble {
            border-radius: 18px;
            padding: 0.85rem 0.95rem;
            margin-bottom: 0.8rem;
            line-height: 1.5;
            animation: cardIn 0.25s ease-out;
        }
        .chat-user {
            background: rgba(71, 198, 219, 0.1);
            border: 1px solid rgba(71, 198, 219, 0.15);
        }
        .chat-assistant {
            background: rgba(255, 255, 255, 0.04);
            border: 1px solid rgba(157, 179, 190, 0.1);
        }
        .chat-label {
            font-size: 0.75rem;
            text-transform: uppercase;
            letter-spacing: 0.05em;
            font-weight: 700;
            margin-bottom: 0.3rem;
            color: rgba(157, 179, 190, 0.78);
        }
        .upload-note {
            display: flex;
            align-items: center;
            gap: 0.55rem;
            color: rgba(134, 223, 236, 0.82);
            margin-bottom: 0.75rem;
        }
        .upload-note svg {
            width: 18px;
            height: 18px;
        }
        .stButton > button {
            background: linear-gradient(135deg, var(--cyan), var(--cyan-soft));
            color: #071e24;
            font-weight: 700;
            border-radius: 14px;
            padding: 0.6em 1.25em;
            border: none;
            box-shadow: 0 10px 20px rgba(71, 198, 219, 0.18);
            transition: transform 0.15s ease, box-shadow 0.15s ease;
        }
        .stButton > button:hover {
            transform: translateY(-1px);
            box-shadow: 0 14px 28px rgba(71, 198, 219, 0.22);
        }
        .stTextInput > div > div > input {
            border-radius: 14px;
            background-color: rgba(30, 40, 47, 0.96);
            color: #eef9fb;
            border: 1px solid rgba(134, 223, 236, 0.12);
        }
        [data-testid="stFileUploader"] {
            background: rgba(24, 31, 38, 0.9);
            border-radius: 18px;
            padding: 0.5rem 0.8rem;
            border: 1px dashed rgba(134, 223, 236, 0.22);
        }
        [data-testid="column"] .stButton > button {
            min-height: 3.2rem;
        }
        @keyframes rise {
            from {
                opacity: 0;
                transform: translateY(10px);
            }
            to {
                opacity: 1;
                transform: translateY(0);
            }
        }
        @keyframes cardIn {
            from {
                opacity: 0;
                transform: translateY(6px) scale(0.99);
            }
            to {
                opacity: 1;
                transform: translateY(0) scale(1);
            }
        }
    </style>
    """,
    unsafe_allow_html=True,
)

st.markdown(
    """
    <section class="hero-shell">
        <div class="hero-kicker">Study Deck Builder</div>
        <div class="hero-title">AI Powered Slide Generator for Documents</div>
        <div class="hero-copy">
            Upload a PDF or text file, generate chapter-aware slides, browse them like a mini presentation,
            and keep a chatbot workspace beside the deck for quick follow-up questions.
        </div>
    </section>
    """,
    unsafe_allow_html=True,
)

st.markdown(
    "Drop in a PDF or TXT file to build an interactive study deck."
)

uploaded_file = st.file_uploader("Upload a book (PDF or TXT)", type=["pdf", "txt"])

if uploaded_file:
    file_ext = uploaded_file.name.split('.')[-1].lower()
    with tempfile.NamedTemporaryFile(delete=False, suffix="." + file_ext) as tmp_file:
        tmp_file.write(uploaded_file.read())
        tmp_path = tmp_file.name

    # Button to trigger slide generation
    if st.button("Generate Slides from Text"):
        st.info(f"Generating Slides from the Uploaded {file_ext.upper()}: {uploaded_file.name}")
        with st.spinner("Generating slides..."):
            try:
                status, json_path = main(tmp_path)
                if status == 1:
                    _load_slides_into_state(json_path)
            except Exception as e:
                st.error(f"Failed to generate slides: {e}")
                st.session_state.slides_generated = False

if st.session_state.get("slides_generated", False):
    # Retrieve slides data from session state
    slides_dict = st.session_state.get("slides_dict", None)

    if slides_dict:
        # Flatten slides into a list of (chapter_title, section_title, slide_markdown_list)
        all_slides = [
            (chapter, section, slide_markdown_list)
            for chapter, sections in slides_dict.items()
            for section, slide_markdown_list in sections.items()
        ]

        # Initialize slide index
        if "slide_index" not in st.session_state or st.session_state.slide_index >= len(all_slides):
            st.session_state.slide_index = 0

        if all_slides:
            chapter_title, section_title, slide_markdown_list = all_slides[st.session_state.slide_index]
            total_cards = len(all_slides)
            current_card = st.session_state.slide_index + 1

            left_col, right_col = st.columns([1.45, 0.95], gap="large")

            with left_col:
                st.markdown(
                    f"""
                    <div class="panel">
                        <div class="panel-title">{SLIDE_ICON}<span>Slides Interface</span></div>
                        <div class="meta-strip">
                            <div class="meta-card">
                                <div class="meta-label">Current Chapter</div>
                                <div class="meta-value">{chapter_title}</div>
                            </div>
                            <div class="meta-card">
                                <div class="meta-label">Current Section</div>
                                <div class="meta-value">{section_title}</div>
                            </div>
                            <div class="meta-card">
                                <div class="meta-label">Deck Position</div>
                                <div class="meta-value">{current_card} / {total_cards}</div>
                            </div>
                        </div>
                    </div>
                    """,
                    unsafe_allow_html=True,
                )

                stage_left, stage_mid, stage_right = st.columns([0.18, 1, 0.18], gap="small")
                with stage_left:
                    st.markdown("<div class='nav-rail'>", unsafe_allow_html=True)
                    if st.button("◀", disabled=st.session_state.slide_index == 0, use_container_width=True, key="prev_side"):
                        st.session_state.slide_index -= 1
                        st.rerun()
                    st.markdown("</div>", unsafe_allow_html=True)
                with stage_mid:
                    for slide_markdown in slide_markdown_list:
                        lines = [line for line in slide_markdown.splitlines() if line.strip()]
                        title = lines[0][2:] if lines and lines[0].startswith("# ") else "Slide"
                        body_lines = lines[1:] if len(lines) > 1 else []
                        body_html = "".join(
                            f"<div class='slide-line {'slide-heading' if line.startswith('## ') else ''}'>{line[3:] if line.startswith('## ') else line}</div>"
                            for line in body_lines
                        )
                        st.markdown(
                            f"""
                            <div class="slide-card">
                                <div class="slide-title">{title}</div>
                                {body_html}
                            </div>
                            """,
                            unsafe_allow_html=True,
                        )
                with stage_right:
                    st.markdown("<div class='nav-rail'>", unsafe_allow_html=True)
                    if st.button(
                        "▶",
                        disabled=st.session_state.slide_index == len(all_slides) - 1,
                        use_container_width=True,
                        key="next_side",
                    ):
                        st.session_state.slide_index += 1
                        st.rerun()
                    st.markdown("</div>", unsafe_allow_html=True)

                download_col, spacer_col = st.columns([0.42, 0.58], gap="small")
                with download_col:
                    st.download_button(
                        "Download Slides",
                        data=st.session_state.get("pptx_bytes", b""),
                        file_name="book_slides.pptx",
                        mime="application/vnd.openxmlformats-officedocument.presentationml.presentation",
                        use_container_width=True,
                    )

                st.caption(f"Slides data is stored temporarily at: {st.session_state.json_path}")

            with right_col:
                st.markdown(
                    f"""
                    <div class="panel">
                        <div class="panel-title">{CHAT_ICON}<span>Chatbot Workspace</span></div>
                        <div style="color: rgba(217, 230, 236, 0.72); margin-bottom: 0.9rem;">
                            Ask follow-up questions about the active section. If Gemini quota is unavailable,
                            the error will appear here without affecting the slide deck.
                        </div>
                    </div>
                    """,
                    unsafe_allow_html=True,
                )

                if "chat_history" not in st.session_state:
                    st.session_state.chat_history = []

                st.markdown("<div class='chat-shell'>", unsafe_allow_html=True)
                if st.session_state.chat_history:
                    for chat in st.session_state.chat_history[::-1]:
                        _render_chat_message(chat["role"], chat["text"])
                else:
                    st.markdown(
                        """
                        <div class="chat-bubble chat-assistant">
                            <div class="chat-label">Assistant</div>
                            Ask about the current section once slides are loaded.
                        </div>
                        """,
                        unsafe_allow_html=True,
                    )
                st.markdown("</div>", unsafe_allow_html=True)

                question = st.text_input("Type your question here:", key="chat_question")
                if question:
                    with st.spinner("Thinking..."):
                        try:
                            import google.generativeai as genai

                            client = genai.GenerativeModel("gemini-2.0-flash")
                            response = client.generate_content(
                                f"""
                                You are provided the following slide content from a book.

                                Chapter: {chapter_title}
                                Section: {section_title}

                                Slides:
                                {_slides_to_plain_text(slide_markdown_list)}

                                Answer this question briefly and clearly:
                                {question}
                                """
                            )
                            answer = response.text.strip()
                            st.session_state.chat_history.append({"role": "user", "text": question})
                            st.session_state.chat_history.append({"role": "assistant", "text": answer})
                        except Exception as e:
                            st.session_state.chat_history.append({"role": "user", "text": question})
                            st.session_state.chat_history.append({"role": "assistant", "text": f"Error: {e}"})
                    st.rerun()
        else:
            st.warning("No slides available to display.")
